## To run, type: execfile("D:\CIVM_Apps\Slicer\FiberCompareView\\2D_Atlas\\ndLibrary_Test.py")
## Author: Austin Kao
execfile("D:\CIVM_Apps\Slicer\FiberCompareView\\2D_Atlas\\ndLibrary.py")
#f = ndLibrary(None, r"D:\Libraries\010Rat_Brain")
#f = ndLibrary(None, r"D:\CIVM_Apps\Slicer\FiberCompareViewTestData\\090_Heritability")
#f = ndLibrary(None, r"D:\Libraries\010Rat_Brain\v2020-06-25\23Rat")
f = ndLibrary(None, r"D:\Libraries\010Rat_Brain\v2020-06-25\21Rat")
#print("Testing loading of a conf file")
#f.loadConf(r"D:\Libraries\010Rat_Brain\lib.conf")
#print("Testing building children")
#f.buildChildren()
#print("Testing loading entire tree")
#f.loadEntire()
print("End of test")